import { Province, City } from '@/types';

export const PROVINCES: Province[] = [
  { id: 'santa-fe', name: 'Santa Fe', slug: 'santa-fe' },
  { id: 'entre-rios', name: 'Entre Ríos', slug: 'entre-rios' },
  { id: 'all', name: 'Todas las provincias', slug: 'todas' },
];

export const CITIES_SANTA_FE: City[] = [
  {
    id: 'rosario',
    name: 'Rosario',
    slug: 'rosario',
    department: 'Rosario',
    description: 'Polo comercial, industrial y gastronómico a orillas del río Paraná.',
    imageUrl: '/images/city-parana.jpg',
    isFeatured: true,
    commerceCount: 450,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'santa-fe-capital',
    name: 'Santa Fe Capital',
    slug: 'santa-fe-capital',
    department: 'La Capital',
    description: 'Capital provincial, centro administrativo, universitario y cultural.',
    imageUrl: '/images/city-concordia.jpg',
    isFeatured: true,
    commerceCount: 380,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'rafaela',
    name: 'Rafaela',
    slug: 'rafaela',
    department: 'Castellanos',
    description: 'Corazón productivo e industrial del oeste santafesino.',
    imageUrl: '/images/city-colon.jpg',
    isFeatured: true,
    commerceCount: 190,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'venado-tuerto',
    name: 'Venado Tuerto',
    slug: 'venado-tuerto',
    department: 'General López',
    description: 'Centro agroindustrial y comercial del sur de Santa Fe.',
    imageUrl: '/images/city-gualeguaychu.jpg',
    isFeatured: false,
    commerceCount: 140,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'reconquista',
    name: 'Reconquista',
    slug: 'reconquista',
    department: 'General Obligado',
    description: 'Polo comercial y agroganadero del norte santafesino.',
    imageUrl: '/images/city-concepcion.jpg',
    isFeatured: false,
    commerceCount: 110,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'santo-tome',
    name: 'Santo Tomé',
    slug: 'santo-tome',
    department: 'La Capital',
    description: 'Ciudad vecina conectada al área metropolitana santafesina.',
    imageUrl: '/images/city-federacion.jpg',
    isFeatured: false,
    commerceCount: 85,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
  {
    id: 'esperanza',
    name: 'Esperanza',
    slug: 'esperanza',
    department: 'Las Colonias',
    description: 'Primera colonia agrícola organizada de la República Argentina.',
    imageUrl: '/images/city-villaelisa.jpg',
    isFeatured: false,
    commerceCount: 95,
    provinceId: 'santa-fe',
    provinceName: 'Santa Fe',
  },
];

export const CITIES_ENTRE_RIOS: City[] = [
  {
    id: 'parana',
    name: 'Paraná',
    slug: 'parana',
    department: 'Paraná',
    description: 'Capital provincial de Entre Ríos con barrancas al río Paraná.',
    imageUrl: '/images/city-parana.jpg',
    isFeatured: true,
    commerceCount: 310,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'concordia',
    name: 'Concordia',
    slug: 'concordia',
    department: 'Concordia',
    description: 'Capital nacional del citrus y termas a orillas del río Uruguay.',
    imageUrl: '/images/city-concordia.jpg',
    isFeatured: true,
    commerceCount: 240,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'colon',
    name: 'Colón',
    slug: 'colon',
    department: 'Colón',
    description: 'Destino turístico con playas de arena blanca y termas.',
    imageUrl: '/images/city-colon.jpg',
    isFeatured: true,
    commerceCount: 180,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'gualeguaychu',
    name: 'Gualeguaychú',
    slug: 'gualeguaychu',
    department: 'Gualeguaychú',
    description: 'Bodegas boutique, enoturismo y eventos culturales.',
    imageUrl: '/images/city-gualeguaychu.jpg',
    isFeatured: true,
    commerceCount: 210,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'concepcion-del-uruguay',
    name: 'Concepción del Uruguay',
    slug: 'concepcion-del-uruguay',
    department: 'Uruguay',
    description: 'Ciudad histórica con puerto y polo universitario.',
    imageUrl: '/images/city-concepcion.jpg',
    isFeatured: false,
    commerceCount: 160,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'federacion',
    name: 'Federación',
    slug: 'federacion',
    department: 'Federación',
    description: 'Ciudad termal pionera a orillas del lago Salto Grande.',
    imageUrl: '/images/city-federacion.jpg',
    isFeatured: false,
    commerceCount: 120,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'villa-elisa',
    name: 'Villa Elisa',
    slug: 'villa-elisa',
    department: 'Colón',
    description: 'Jardín de Entre Ríos con complejo termal.',
    imageUrl: '/images/city-villaelisa.jpg',
    isFeatured: false,
    commerceCount: 90,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
  {
    id: 'chajari',
    name: 'Chajarí',
    slug: 'chajari',
    department: 'Federación',
    description: 'Polo citrícola y termal del noreste entrerriano.',
    imageUrl: '/images/city-chajari.jpg',
    isFeatured: false,
    commerceCount: 105,
    provinceId: 'entre-rios',
    provinceName: 'Entre Ríos',
  },
];

export const ALL_CITIES: City[] = [...CITIES_SANTA_FE, ...CITIES_ENTRE_RIOS];

export function getCitiesByProvince(provinceId: string): City[] {
  if (!provinceId || provinceId === 'all') {
    return ALL_CITIES;
  }
  return ALL_CITIES.filter((city) => city.provinceId === provinceId);
}

export function getProvinceById(provinceId: string): Province | undefined {
  return PROVINCES.find((p) => p.id === provinceId);
}
